version: "2.4"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    networks:
    - gpl-network
    volumes:
    - mysql_data:/var/lib/mysql
  batch:
    build: .
    volumes:
      - ./config:/app/config
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
    ports:
      - "8080:8080"
    networks:
    - gpl-network
    depends_on:
      mysql:
        condition: service_started
    restart: always
volumes:
  mysql_data: {}
networks:
  gpl-network:
    driver: bridge

